### ISSUE TITLE
Encoding Decoding Map to JSON

### ISSUE THREAD

**Issue by carlos-verdes** [zio/zio-schema#447]
How to reproduce, create a case class with an optional field of type Map:
```scala
case class ServerVersion(
    server: String,
    license: String,
    version: String,
    details: Map[String, String] = Map.empty
)

given Schema[ServerVersion] = DeriveSchema.gen[ServerVersion]
```

Expected test to pass:
```scala

      test("Encode/Decode ServerInfo from json using schema") {
        for
          _ <- ZIO.unit
          json = """{ "server": "arango", "license": "community", "version": "3.10.1"}"""
          chunks = Chunk.fromArray(json.getBytes)
          serverInfo <- ZIO.fromEither(
            JsonCodec.decode[ServerVersion](given_Schema_ServerVersion)(chunks)
          )
        yield assertTrue(
          serverInfo == ServerVersion("arango", "community", "3.10.1")
        )
      }
```

Error: the field details is decoded as `Map("" -> "" )`   instead of `Map.empty`:
![image](https://user-images.githubusercontent.com/8631522/204472252-6326d63e-1567-4d23-b0ba-8a5afd3b6211.png)

I tried also with next annotations:
```scala
import zio.schema.annotation.{fieldDefaultValue, optionalField}

case class ServerVersion(
    server: String,
    license: String,
    version: String,
    @optionalField
    @fieldDefaultValue[Map[String, String]](Map.empty)
    details: Map[String, String] = Map.empty
)
```

**Comment by carlos-verdes** [comment]
I checked the Spec and I see Map is encoded as a sequence of tuples like:
```js
[
  {"key1":  value1},
  {"key2":  value2}
]
```

However the expectation for me is:
```js
{
  "key1":  value1,
  "key2":  value2
}
```

I think we should change the full implementation of Map encoder/decoder not just the default values

**Comment by carlos-verdes** [comment]
@jdegoes @thinkharderdev @devsprint  @tusharmath 

This is a big problem to use in any API, I have to receive/pass very often Map[String, String] for extra configuration (for example is you use Spark) and it's really weird that is mapped to json [] instead of {}

I implemented a library for ArangoDB using zio-http and zio-json for serialization and I'm now trying to support zio-schema on top of that (so you can use ArangoDB with any type that has an Schema, and I plan to do dynamic graph queries that bring more than 1 entity just from the Schema abstraction)

**Comment by Andrapyre** [comment]
@adamgfraser , maybe you want to claim a bounty for this?

**Comment by 987Nabil** [comment]
@jdegoes this issue still pops up on algora as an open bounty. Maybe you can remove the bounty?
